# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Distribute app to Firebase App Distribution"
  lane :firebase_distribute do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
      app: "1:953262432976:android:e4bee7bc51470e6ecd74d5",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "alpoplast2@gmail.com",
      release_notes: "New beta build with latest features and bug fixes"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
